// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  dropdown: dynamic(() => import("./Dropdown")),
  menu_link: dynamic(() => import("./MenuLink")),
  text: dynamic(() => import("./Text")),
};
