// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  contact_form: dynamic(() => import("./ContactForm")),
  dropdown: dynamic(() => import("./Dropdown")),
  menu_link: dynamic(() => import("./MenuLink")),
  text: dynamic(() => import("./Text")),
  video_gallery: dynamic(() => import("./VideoGallery")),
};
