import { Metadata } from "next";
import { notFound } from "next/navigation";
import { SliceZone } from "@prismicio/react";
import { createClient } from "@/prismicio";
import { components } from "@/slices";
import { PrismicRichText } from "@prismicio/react";
import { PrismicNextLink, PrismicNextImage } from "@prismicio/next";

export default async function Page() {
    const client = createClient();
    const page = await client.getSingle("blog").catch(() => notFound());

    // Fetch blog posts
    // Note: We use 'any' for post type here temporarily until types are regenerated by Slice Machine
    const posts = await client.getAllByType("blog_post", {
        orderings: [
            { field: "my.blog_post.date", direction: "desc" }
        ],
    });

    return (
        <div className="min-h-screen bg-white dark:bg-zinc-950 text-zinc-900 dark:text-zinc-100">
            <SliceZone slices={page.data.slices} components={components} />

            <div className="max-w-6xl mx-auto px-6 py-12">
                <h2 className="text-3xl font-bold mb-8">Latest Posts</h2>
                {posts.length === 0 ? (
                    <p className="text-zinc-500">No posts found.</p>
                ) : (
                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-10">
                        {posts.map((post) => (
                            <article key={post.id} className="group relative flex flex-col items-start justify-between">
                                <div className="relative w-full aspect-[16/9] mb-4 overflow-hidden rounded-2xl bg-zinc-100 dark:bg-zinc-800 border border-zinc-200 dark:border-zinc-800">
                                    {post.data.featured_image?.url && (
                                        <PrismicNextImage
                                            field={post.data.featured_image}
                                            fill
                                            className="object-cover transition-transform duration-500 group-hover:scale-105"
                                        />
                                    )}
                                </div>
                                <div className="flex items-center gap-x-4 text-xs text-zinc-500 dark:text-zinc-400">
                                    {post.data.date && (
                                        <time dateTime={post.data.date}>
                                            {new Date(post.data.date).toLocaleDateString(undefined, {
                                                year: 'numeric',
                                                month: 'long',
                                                day: 'numeric'
                                            })}
                                        </time>
                                    )}
                                </div>
                                <div className="group relative mt-3">
                                    <h3 className="text-xl font-semibold leading-6 group-hover:text-blue-600 dark:group-hover:text-blue-400 transition-colors">
                                        <PrismicNextLink document={post}>
                                            <span className="absolute inset-0" />
                                            <PrismicRichText field={post.data.title} />
                                        </PrismicNextLink>
                                    </h3>
                                </div>
                            </article>
                        ))}
                    </div>
                )}
            </div>
        </div>
    );
}

export async function generateMetadata(): Promise<Metadata> {
    return {
        title: "Blog",
        description: "Read our latest articles and updates.",
    };
}
